name: book
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.8
  
  # Riverpod
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Network
  dio: ^5.8.0+1
  retrofit: ^4.5.0
  flutter_secure_storage: ^9.2.4

  # Data class / Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0

  # Social Login
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  kakao_flutter_sdk: ^1.9.3

  # UI
  flutter_svg: ^2.0.10+1
  openid_client: ^0.4.9

  go_router: ^14.2.0

  # New dependency
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.5

  # Code generation
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  retrofit_generator: ^9.3.0
  flutter_gen_runner: ^5.10.0

dependency_overrides:
  build: '2.5.4'

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/