name: book
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker:

  # Core
  cupertino_icons: ^1.0.8
  
  # Riverpod
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Network
  dio: ^5.8.0+1
  retrofit: ^4.5.0
  flutter_secure_storage: ^9.2.4

  # Data class / Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0

  # Social Login
  google_sign_in: ^6.2.1
  sign_in_with_apple:
  kakao_flutter_sdk: ^1.9.3

  # UI
  flutter_svg: ^2.0.10+1
  openid_client: ^0.4.9

  go_router: ^14.2.0

  # New dependency
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.4.1
  mime: ^1.0.5

  # Firebase
  firebase_auth:
  firebase_core:
  sleek_circular_slider: ^2.0.1
  flutter_rating_bar: ^4.0.1
  collection: ^1.19.1
  ably_flutter: ^1.2.40
  intl: ^0.20.2
  scrollable_positioned_list: ^0.3.8
  flutter_slidable: ^4.0.0
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.2
  html_unescape: ^2.0.0

  # audio
  audio_session: ^0.2.2
  just_audio: ^0.10.4
  
  # Bar
  flutter_xlider: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.5

  # Code generation
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  retrofit_generator: ^9.3.0
  flutter_gen_runner: ^5.10.0

  
  
dependency_overrides:
  build: '2.5.4'

flutter:
  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
  assets:
    - assets/env/.env
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/sample_book.jpg

flutter_gen:
  output: lib/gen/
  integrations:
    image: true
    flutter_svg: true
  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
